/* automatically generated by rust-bindgen 0.65.1 */

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
use crate::types::*;

pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const IR_VERSION_MAJOR: u32 = 0;
pub const IR_VERSION_MINOR: u32 = 1;
pub const IR_VERSION_PATCH: u32 = 0;
pub const IRDescriptorRangeOffsetAppend: u32 = 4294967295;
pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
pub type va_list = *mut ::std::os::raw::c_char;
pub type __vcrt_bool = bool;
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
extern crate libloading;
pub struct metal_irconverter {
    __library: ::libloading::Library,
    pub IRErrorGetCode: unsafe extern "C" fn(error: *const IRErrorOpaque) -> u32,
    pub IRErrorGetPayload:
        unsafe extern "C" fn(error: *const IRErrorOpaque) -> *const ::std::os::raw::c_void,
    pub IRErrorDestroy: unsafe extern "C" fn(error: *mut IRErrorOpaque),
    pub IRRootSignatureCreateFromDescriptor: unsafe extern "C" fn(
        descriptor: *const IRVersionedRootSignatureDescriptor,
        error: *mut *mut IRErrorOpaque,
    )
        -> *mut IRRootSignatureOpaque,
    pub IRRootSignatureDestroy: unsafe extern "C" fn(sig: *mut IRRootSignatureOpaque),
    pub IRObjectCreateFromDXIL: unsafe extern "C" fn(
        bytecode: *const u8,
        size: usize,
        bytecodeOwnership: IRBytecodeOwnership,
    ) -> *mut IRObjectOpaque,
    pub IRObjectDestroy: unsafe extern "C" fn(object: *mut IRObjectOpaque),
    pub IRObjectGetType: unsafe extern "C" fn(object: *const IRObjectOpaque) -> IRObjectType,
    pub IRObjectGetMetalIRShaderStage:
        unsafe extern "C" fn(object: *const IRObjectOpaque) -> IRShaderStage,
    pub IRCompilerSetValidationFlags: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        validationFlags: IRCompilerValidationFlags,
    ),
    pub IRCompilerCreate: unsafe extern "C" fn() -> *mut IRCompilerOpaque,
    pub IRCompilerDestroy: unsafe extern "C" fn(compiler: *mut IRCompilerOpaque),
    pub IRCompilerAllocCompileAndLink: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        entryPointNames: *const *const ::std::os::raw::c_char,
        entryPointCount: usize,
        input: *const IRObjectOpaque,
        error: *mut *mut IRErrorOpaque,
    ) -> *mut IRObjectOpaque,
    pub IRObjectGetMetalLibBinary: unsafe extern "C" fn(
        obj: *const IRObjectOpaque,
        stage: IRShaderStage,
        lib: *mut IRMetalLibBinaryOpaque,
    ) -> bool,
    pub IRCompilerSetStageInGenerationMode: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        stageInCodeGenerationMode: IRStageInCodeGenerationMode,
    ),
    pub IRMetalLibSynthesizeStageInFunction: unsafe extern "C" fn(
        compiler: *const IRCompilerOpaque,
        vertexShaderReflection: *const IRShaderReflectionOpaque,
        layout: *const IRVersionedInputLayoutDescriptor,
        binary: *mut IRMetalLibBinaryOpaque,
    ) -> bool,
    pub IRObjectGetReflection: unsafe extern "C" fn(
        obj: *const IRObjectOpaque,
        stage: IRShaderStage,
        reflection: *mut IRShaderReflectionOpaque,
    ) -> bool,
    pub IRCompilerSetGlobalRootSignature: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        rootSignature: *const IRRootSignatureOpaque,
    ),
    pub IRCompilerSetCompatibilityFlags:
        unsafe extern "C" fn(compiler: *mut IRCompilerOpaque, flags: IRCompatibilityFlags),
    pub IRCompilerSetInputTopology:
        unsafe extern "C" fn(compiler: *mut IRCompilerOpaque, inputTopology: IRInputTopology),
    pub IRCompilerEnableGeometryAndTessellationEmulation:
        unsafe extern "C" fn(compiler: *mut IRCompilerOpaque, enable: bool),
    pub IRCompilerSetDualSourceBlendingConfiguration: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        configuration: IRDualSourceBlendingConfiguration,
    ),
    pub IRCompilerSetDepthFeedbackConfiguration: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        configuration: IRDepthFeedbackConfiguration,
    ),
    pub IRCompilerSetEntryPointName: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        newName: *const ::std::os::raw::c_char,
    ),
    pub IRCompilerSetMinimumGPUFamily:
        unsafe extern "C" fn(compiler: *mut IRCompilerOpaque, family: IRGPUFamily),
    pub IRCompilerSetMinimumDeploymentTarget: unsafe extern "C" fn(
        compiler: *mut IRCompilerOpaque,
        operatingSystem: IROperatingSystem,
        version: *const ::std::os::raw::c_char,
    ),
    pub IRMetalLibBinaryCreate: unsafe extern "C" fn() -> *mut IRMetalLibBinaryOpaque,
    pub IRMetalLibBinaryDestroy: unsafe extern "C" fn(lib: *mut IRMetalLibBinaryOpaque),
    pub IRMetalLibGetBytecode:
        unsafe extern "C" fn(lib: *const IRMetalLibBinaryOpaque, outBytecode: *mut u8) -> usize,
    pub IRMetalLibGetBytecodeSize:
        unsafe extern "C" fn(lib: *const IRMetalLibBinaryOpaque) -> usize,
    pub IRObjectSerialize: unsafe extern "C" fn(
        outputPath: *const ::std::os::raw::c_char,
        obj: *const IRObjectOpaque,
        stage: IRShaderStage,
    ) -> bool,
    pub IRShaderReflectionCreate: unsafe extern "C" fn() -> *mut IRShaderReflectionOpaque,
    pub IRShaderReflectionDestroy: unsafe extern "C" fn(reflection: *mut IRShaderReflectionOpaque),
    pub IRShaderReflectionGetEntryPointFunctionName:
        unsafe extern "C" fn(
            reflection: *const IRShaderReflectionOpaque,
        ) -> *const ::std::os::raw::c_char,
    pub IRShaderReflectionNeedsFunctionConstants:
        unsafe extern "C" fn(reflection: *const IRShaderReflectionOpaque) -> bool,
    pub IRShaderReflectionGetFunctionConstantCount:
        unsafe extern "C" fn(reflection: *const IRShaderReflectionOpaque) -> usize,
    pub IRShaderReflectionCopyFunctionConstants: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        functionConstants: *mut IRFunctionConstant,
    ),
    pub IRShaderReflectionReleaseFunctionConstants: unsafe extern "C" fn(
        functionConstants: *mut IRFunctionConstant,
        functionConstantCount: usize,
    ),
    pub IRShaderReflectionCopyComputeInfo: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        csinfo: *mut IRVersionedCSInfo,
    ) -> bool,
    pub IRShaderReflectionCopyVertexInfo: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        vsinfo: *mut IRVersionedVSInfo,
    ) -> bool,
    pub IRShaderReflectionCopyFragmentInfo: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        fsinfo: *mut IRVersionedFSInfo,
    ) -> bool,
    pub IRShaderReflectionCopyGeometryInfo: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        gsinfo: *mut IRVersionedGSInfo,
    ) -> bool,
    pub IRShaderReflectionCopyHullInfo: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        hsinfo: *mut IRVersionedHSInfo,
    ) -> bool,
    pub IRShaderReflectionCopyDomainInfo: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        dsinfo: *mut IRVersionedDSInfo,
    ) -> bool,
    pub IRShaderReflectionReleaseComputeInfo:
        unsafe extern "C" fn(csinfo: *mut IRVersionedCSInfo) -> bool,
    pub IRShaderReflectionReleaseVertexInfo:
        unsafe extern "C" fn(vsinfo: *mut IRVersionedVSInfo) -> bool,
    pub IRShaderReflectionReleaseFragmentInfo:
        unsafe extern "C" fn(fsinfo: *mut IRVersionedFSInfo) -> bool,
    pub IRShaderReflectionReleaseGeometryInfo:
        unsafe extern "C" fn(gsinfo: *mut IRVersionedGSInfo) -> bool,
    pub IRShaderReflectionReleaseHullInfo:
        unsafe extern "C" fn(hsinfo: *mut IRVersionedHSInfo) -> bool,
    pub IRShaderReflectionReleaseDomainInfo:
        unsafe extern "C" fn(dsinfo: *mut IRVersionedDSInfo) -> bool,
    pub IRShaderReflectionGetResourceCount:
        unsafe extern "C" fn(reflection: *const IRShaderReflectionOpaque) -> usize,
    pub IRShaderReflectionGetResourceLocations: unsafe extern "C" fn(
        reflection: *const IRShaderReflectionOpaque,
        resourceLocations: *mut IRResourceLocation,
    ),
    pub IRRootSignatureGetResourceCount:
        unsafe extern "C" fn(rootSignature: *const IRRootSignatureOpaque) -> usize,
    pub IRRootSignatureGetResourceLocations: unsafe extern "C" fn(
        rootSignature: *const IRRootSignatureOpaque,
        resourceLocations: *mut IRResourceLocation,
    ),
    pub IRShaderReflectionSerialize: unsafe extern "C" fn(
        reflection: *mut IRShaderReflectionOpaque,
    ) -> *const ::std::os::raw::c_char,
    pub IRShaderReflectionDeserialize: unsafe extern "C" fn(
        blob: *const ::std::os::raw::c_char,
        reflection: *mut IRShaderReflectionOpaque,
    ),
}
impl metal_irconverter {
    pub unsafe fn new<P>(path: P) -> Result<Self, ::libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let library = ::libloading::Library::new(path)?;
        Self::from_library(library)
    }
    pub unsafe fn from_library<L>(library: L) -> Result<Self, ::libloading::Error>
    where
        L: Into<::libloading::Library>,
    {
        let __library = library.into();
        let IRErrorGetCode = __library.get(b"IRErrorGetCode\0").map(|sym| *sym)?;
        let IRErrorGetPayload = __library.get(b"IRErrorGetPayload\0").map(|sym| *sym)?;
        let IRErrorDestroy = __library.get(b"IRErrorDestroy\0").map(|sym| *sym)?;
        let IRRootSignatureCreateFromDescriptor = __library
            .get(b"IRRootSignatureCreateFromDescriptor\0")
            .map(|sym| *sym)?;
        let IRRootSignatureDestroy = __library.get(b"IRRootSignatureDestroy\0").map(|sym| *sym)?;
        let IRObjectCreateFromDXIL = __library.get(b"IRObjectCreateFromDXIL\0").map(|sym| *sym)?;
        let IRObjectDestroy = __library.get(b"IRObjectDestroy\0").map(|sym| *sym)?;
        let IRObjectGetType = __library.get(b"IRObjectGetType\0").map(|sym| *sym)?;
        let IRObjectGetMetalIRShaderStage = __library
            .get(b"IRObjectGetMetalIRShaderStage\0")
            .map(|sym| *sym)?;
        let IRCompilerSetValidationFlags = __library
            .get(b"IRCompilerSetValidationFlags\0")
            .map(|sym| *sym)?;
        let IRCompilerCreate = __library.get(b"IRCompilerCreate\0").map(|sym| *sym)?;
        let IRCompilerDestroy = __library.get(b"IRCompilerDestroy\0").map(|sym| *sym)?;
        let IRCompilerAllocCompileAndLink = __library
            .get(b"IRCompilerAllocCompileAndLink\0")
            .map(|sym| *sym)?;
        let IRObjectGetMetalLibBinary = __library
            .get(b"IRObjectGetMetalLibBinary\0")
            .map(|sym| *sym)?;
        let IRCompilerSetStageInGenerationMode = __library
            .get(b"IRCompilerSetStageInGenerationMode\0")
            .map(|sym| *sym)?;
        let IRMetalLibSynthesizeStageInFunction = __library
            .get(b"IRMetalLibSynthesizeStageInFunction\0")
            .map(|sym| *sym)?;
        let IRObjectGetReflection = __library.get(b"IRObjectGetReflection\0").map(|sym| *sym)?;
        let IRCompilerSetGlobalRootSignature = __library
            .get(b"IRCompilerSetGlobalRootSignature\0")
            .map(|sym| *sym)?;
        let IRCompilerSetCompatibilityFlags = __library
            .get(b"IRCompilerSetCompatibilityFlags\0")
            .map(|sym| *sym)?;
        let IRCompilerSetInputTopology = __library
            .get(b"IRCompilerSetInputTopology\0")
            .map(|sym| *sym)?;
        let IRCompilerEnableGeometryAndTessellationEmulation = __library
            .get(b"IRCompilerEnableGeometryAndTessellationEmulation\0")
            .map(|sym| *sym)?;
        let IRCompilerSetDualSourceBlendingConfiguration = __library
            .get(b"IRCompilerSetDualSourceBlendingConfiguration\0")
            .map(|sym| *sym)?;
        let IRCompilerSetDepthFeedbackConfiguration = __library
            .get(b"IRCompilerSetDepthFeedbackConfiguration\0")
            .map(|sym| *sym)?;
        let IRCompilerSetEntryPointName = __library
            .get(b"IRCompilerSetEntryPointName\0")
            .map(|sym| *sym)?;
        let IRCompilerSetMinimumGPUFamily = __library
            .get(b"IRCompilerSetMinimumGPUFamily\0")
            .map(|sym| *sym)?;
        let IRCompilerSetMinimumDeploymentTarget = __library
            .get(b"IRCompilerSetMinimumDeploymentTarget\0")
            .map(|sym| *sym)?;
        let IRMetalLibBinaryCreate = __library.get(b"IRMetalLibBinaryCreate\0").map(|sym| *sym)?;
        let IRMetalLibBinaryDestroy = __library
            .get(b"IRMetalLibBinaryDestroy\0")
            .map(|sym| *sym)?;
        let IRMetalLibGetBytecode = __library.get(b"IRMetalLibGetBytecode\0").map(|sym| *sym)?;
        let IRMetalLibGetBytecodeSize = __library
            .get(b"IRMetalLibGetBytecodeSize\0")
            .map(|sym| *sym)?;
        let IRObjectSerialize = __library.get(b"IRObjectSerialize\0").map(|sym| *sym)?;
        let IRShaderReflectionCreate = __library
            .get(b"IRShaderReflectionCreate\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionDestroy = __library
            .get(b"IRShaderReflectionDestroy\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionGetEntryPointFunctionName = __library
            .get(b"IRShaderReflectionGetEntryPointFunctionName\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionNeedsFunctionConstants = __library
            .get(b"IRShaderReflectionNeedsFunctionConstants\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionGetFunctionConstantCount = __library
            .get(b"IRShaderReflectionGetFunctionConstantCount\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyFunctionConstants = __library
            .get(b"IRShaderReflectionCopyFunctionConstants\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseFunctionConstants = __library
            .get(b"IRShaderReflectionReleaseFunctionConstants\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyComputeInfo = __library
            .get(b"IRShaderReflectionCopyComputeInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyVertexInfo = __library
            .get(b"IRShaderReflectionCopyVertexInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyFragmentInfo = __library
            .get(b"IRShaderReflectionCopyFragmentInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyGeometryInfo = __library
            .get(b"IRShaderReflectionCopyGeometryInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyHullInfo = __library
            .get(b"IRShaderReflectionCopyHullInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionCopyDomainInfo = __library
            .get(b"IRShaderReflectionCopyDomainInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseComputeInfo = __library
            .get(b"IRShaderReflectionReleaseComputeInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseVertexInfo = __library
            .get(b"IRShaderReflectionReleaseVertexInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseFragmentInfo = __library
            .get(b"IRShaderReflectionReleaseFragmentInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseGeometryInfo = __library
            .get(b"IRShaderReflectionReleaseGeometryInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseHullInfo = __library
            .get(b"IRShaderReflectionReleaseHullInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionReleaseDomainInfo = __library
            .get(b"IRShaderReflectionReleaseDomainInfo\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionGetResourceCount = __library
            .get(b"IRShaderReflectionGetResourceCount\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionGetResourceLocations = __library
            .get(b"IRShaderReflectionGetResourceLocations\0")
            .map(|sym| *sym)?;
        let IRRootSignatureGetResourceCount = __library
            .get(b"IRRootSignatureGetResourceCount\0")
            .map(|sym| *sym)?;
        let IRRootSignatureGetResourceLocations = __library
            .get(b"IRRootSignatureGetResourceLocations\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionSerialize = __library
            .get(b"IRShaderReflectionSerialize\0")
            .map(|sym| *sym)?;
        let IRShaderReflectionDeserialize = __library
            .get(b"IRShaderReflectionDeserialize\0")
            .map(|sym| *sym)?;
        Ok(metal_irconverter {
            __library,
            IRErrorGetCode,
            IRErrorGetPayload,
            IRErrorDestroy,
            IRRootSignatureCreateFromDescriptor,
            IRRootSignatureDestroy,
            IRObjectCreateFromDXIL,
            IRObjectDestroy,
            IRObjectGetType,
            IRObjectGetMetalIRShaderStage,
            IRCompilerSetValidationFlags,
            IRCompilerCreate,
            IRCompilerDestroy,
            IRCompilerAllocCompileAndLink,
            IRObjectGetMetalLibBinary,
            IRCompilerSetStageInGenerationMode,
            IRMetalLibSynthesizeStageInFunction,
            IRObjectGetReflection,
            IRCompilerSetGlobalRootSignature,
            IRCompilerSetCompatibilityFlags,
            IRCompilerSetInputTopology,
            IRCompilerEnableGeometryAndTessellationEmulation,
            IRCompilerSetDualSourceBlendingConfiguration,
            IRCompilerSetDepthFeedbackConfiguration,
            IRCompilerSetEntryPointName,
            IRCompilerSetMinimumGPUFamily,
            IRCompilerSetMinimumDeploymentTarget,
            IRMetalLibBinaryCreate,
            IRMetalLibBinaryDestroy,
            IRMetalLibGetBytecode,
            IRMetalLibGetBytecodeSize,
            IRObjectSerialize,
            IRShaderReflectionCreate,
            IRShaderReflectionDestroy,
            IRShaderReflectionGetEntryPointFunctionName,
            IRShaderReflectionNeedsFunctionConstants,
            IRShaderReflectionGetFunctionConstantCount,
            IRShaderReflectionCopyFunctionConstants,
            IRShaderReflectionReleaseFunctionConstants,
            IRShaderReflectionCopyComputeInfo,
            IRShaderReflectionCopyVertexInfo,
            IRShaderReflectionCopyFragmentInfo,
            IRShaderReflectionCopyGeometryInfo,
            IRShaderReflectionCopyHullInfo,
            IRShaderReflectionCopyDomainInfo,
            IRShaderReflectionReleaseComputeInfo,
            IRShaderReflectionReleaseVertexInfo,
            IRShaderReflectionReleaseFragmentInfo,
            IRShaderReflectionReleaseGeometryInfo,
            IRShaderReflectionReleaseHullInfo,
            IRShaderReflectionReleaseDomainInfo,
            IRShaderReflectionGetResourceCount,
            IRShaderReflectionGetResourceLocations,
            IRRootSignatureGetResourceCount,
            IRRootSignatureGetResourceLocations,
            IRShaderReflectionSerialize,
            IRShaderReflectionDeserialize,
        })
    }
    #[doc = " Obtain the error code of an error.\n @param error error object to query.\n @return error code."]
    pub unsafe fn IRErrorGetCode(&self, error: *const IRErrorOpaque) -> u32 {
        (self.IRErrorGetCode)(error)
    }
    #[doc = " Obtain any payload associated with an error.\n @param error error object to query.\n @return error payload. You must cast this pointer to the appropriate error payload struct for the error code."]
    pub unsafe fn IRErrorGetPayload(
        &self,
        error: *const IRErrorOpaque,
    ) -> *const ::std::os::raw::c_void {
        (self.IRErrorGetPayload)(error)
    }
    #[doc = " Release resources associated with an error object.\n @param error error objects for which to release its associated resources."]
    pub unsafe fn IRErrorDestroy(&self, error: *mut IRErrorOpaque) {
        (self.IRErrorDestroy)(error)
    }
    #[doc = " Create a new root signature from its descriptor.\n @param descriptor description of the root signature to create.\n @param error on return, if the compiler generates any errors, this optional out parameter contains error information. If an error occurs and this parameter is non-NULL, you must free it by calling IRErrorDestroy.\n @return a new root signature suitable for configuring the top-level argument buffer layout of the produced MetalIR, or NULL upon encountering an error. You must destroy this object by calling IRRootSignatureDestroy."]
    pub unsafe fn IRRootSignatureCreateFromDescriptor(
        &self,
        descriptor: *const IRVersionedRootSignatureDescriptor,
        error: *mut *mut IRErrorOpaque,
    ) -> *mut IRRootSignatureOpaque {
        (self.IRRootSignatureCreateFromDescriptor)(descriptor, error)
    }
    #[doc = " Destroy a root signature object.\n @param sig root signature object to destroy."]
    pub unsafe fn IRRootSignatureDestroy(&self, sig: *mut IRRootSignatureOpaque) {
        (self.IRRootSignatureDestroy)(sig)
    }
    #[doc = " Create a DXIL object from DXIL bytecode.\n @param bytecode bytecode representing legal DXIL. When using IRBytecodeOwnershipNone, you must ensure this buffer is not freed while the returned object is in use.\n @param size size of the bytecode in bytes.\n @param bytecodeOwnership determine whether the IRObject shall copy the bytecode or just hold a weak reference.\n @return a new DXIL object representing the DXIL shader. You must destroy this object by calling IRObjectDestroy."]
    pub unsafe fn IRObjectCreateFromDXIL(
        &self,
        bytecode: *const u8,
        size: usize,
        bytecodeOwnership: IRBytecodeOwnership,
    ) -> *mut IRObjectOpaque {
        (self.IRObjectCreateFromDXIL)(bytecode, size, bytecodeOwnership)
    }
    #[doc = " Destroy a IRObject.\n @param object IRObject to destroy."]
    pub unsafe fn IRObjectDestroy(&self, object: *mut IRObjectOpaque) {
        (self.IRObjectDestroy)(object)
    }
    #[doc = " Query a IRObject's type.\n @param object IRObject to query.\n @return IRObjectTypeDXILBytecode if the object represents DXIL bytecode, IRObjectTypeMetalIRObject if the object represents MetalIR bytecode."]
    pub unsafe fn IRObjectGetType(&self, object: *const IRObjectOpaque) -> IRObjectType {
        (self.IRObjectGetType)(object)
    }
    #[doc = " Query the shader stage of this IRObject.\n @param object IRObject to query.\n @return the shader stage of this IRObject."]
    pub unsafe fn IRObjectGetMetalIRShaderStage(
        &self,
        object: *const IRObjectOpaque,
    ) -> IRShaderStage {
        (self.IRObjectGetMetalIRShaderStage)(object)
    }
    #[doc = " Set a compiler's compile-time validation flags.\n @param compiler compiler for which to set the flags.\n @param validationFlags validation flags denoting the checks the compiler performs."]
    pub unsafe fn IRCompilerSetValidationFlags(
        &self,
        compiler: *mut IRCompilerOpaque,
        validationFlags: IRCompilerValidationFlags,
    ) {
        (self.IRCompilerSetValidationFlags)(compiler, validationFlags)
    }
    #[doc = " Create a new compiler instance.\n @return a new compiler instance. You must destroy this object by calling IRCompilerDestroy."]
    pub unsafe fn IRCompilerCreate(&self) -> *mut IRCompilerOpaque {
        (self.IRCompilerCreate)()
    }
    #[doc = " Destroy a compiler instance.\n @param compiler compiler to destroy."]
    pub unsafe fn IRCompilerDestroy(&self, compiler: *mut IRCompilerOpaque) {
        (self.IRCompilerDestroy)(compiler)
    }
    #[doc = " Allocate a new object and populate it with the results of compiling and linking IR bytecode.\n @param compiler compiler to use for the translation process.\n @param entryPointNames array of entry point names to compile (for ray tracing shaders).\n @param input input IR object.\n @param error on return, if the compiler generates any errors, this optional out parameter contains error information. If an error occurs and this parameter is non-NULL, you must free it by calling IRErrorDestroy.\n @return an IR Object containing MetalIR compiled from the input IR, or NULL if an error occurs. You must destroy this object by calling IRObjectDestroy."]
    pub unsafe fn IRCompilerAllocCompileAndLink(
        &self,
        compiler: *mut IRCompilerOpaque,
        entryPointNames: *const *const ::std::os::raw::c_char,
        entryPointCount: usize,
        input: *const IRObjectOpaque,
        error: *mut *mut IRErrorOpaque,
    ) -> *mut IRObjectOpaque {
        (self.IRCompilerAllocCompileAndLink)(
            compiler,
            entryPointNames,
            entryPointCount,
            input,
            error,
        )
    }
    #[doc = " Copy the metallib binary, containing MetalIR bytecode.\n @param obj MetalIR object containing the bytecode from where to copy.\n @param stage shader stage to copy.\n @param lib metallib binary into which to copy the metallib.\n @return true if the metallib binary contains bytecode for this shader stage, false otherwise."]
    pub unsafe fn IRObjectGetMetalLibBinary(
        &self,
        obj: *const IRObjectOpaque,
        stage: IRShaderStage,
        lib: *mut IRMetalLibBinaryOpaque,
    ) -> bool {
        (self.IRObjectGetMetalLibBinary)(obj, stage, lib)
    }
    #[doc = " Configure whether the compiler should generate a Metal vertex fetch, or allow synthesizing a separate stage-in function.\n Use Metal vertex fetch to specify a MTLVertexDescriptor to your pipelines at runtime. Request a separate stage-in function to link vertex fetch as a Metal linked function.\n Using a separate stage-in function provides your shader with more flexitibility to perform type conversions, however, it requires more work to set up.\n @param compiler compiler to configure.\n @param stageInCodeGenerationMode code generation mode for the stage-in function."]
    pub unsafe fn IRCompilerSetStageInGenerationMode(
        &self,
        compiler: *mut IRCompilerOpaque,
        stageInCodeGenerationMode: IRStageInCodeGenerationMode,
    ) {
        (self.IRCompilerSetStageInGenerationMode)(compiler, stageInCodeGenerationMode)
    }
    #[doc = " Synthesize a stage in function.\n @param compiler compiler configuration to use.\n @param vertexShaderReflection reflection object of a vertex stage containing the inputs used as a base for synthesis.\n @param layout vertex input layout descriptor.\n @param binary pointer to a binary into which to write the synthesized MetalIR.\n @return true if the stageIn function could be successfully created, false otherwise."]
    pub unsafe fn IRMetalLibSynthesizeStageInFunction(
        &self,
        compiler: *const IRCompilerOpaque,
        vertexShaderReflection: *const IRShaderReflectionOpaque,
        layout: *const IRVersionedInputLayoutDescriptor,
        binary: *mut IRMetalLibBinaryOpaque,
    ) -> bool {
        (self.IRMetalLibSynthesizeStageInFunction)(compiler, vertexShaderReflection, layout, binary)
    }
    #[doc = " Copy reflection data stemming from the process of compiling DXIL to MetalIR.\n @param obj MetalIR object containing the metadata to copy.\n @param stage shader stage from where to obtain the reflection.\n @param reflection reflection object into which to copy the reflection data.\n @return true if the metallib binary contains bytecode for this shader stage, false otherwise."]
    pub unsafe fn IRObjectGetReflection(
        &self,
        obj: *const IRObjectOpaque,
        stage: IRShaderStage,
        reflection: *mut IRShaderReflectionOpaque,
    ) -> bool {
        (self.IRObjectGetReflection)(obj, stage, reflection)
    }
    #[doc = " Configure a compiler to emit a shader that consumes a top-level Argument Buffer layout matching a specific root signature.\n @param compiler compiler to configure.\n @param rootSignature root signature that defines the layout of the top-level Argument Buffer for any shaders you compile with this compiler.\n Pass in NULL (the default) to have the compiler generate a linear resource layout instead. If you provide a non-NULL rootSignature, you must ensure it is not destroyed before the compiler."]
    pub unsafe fn IRCompilerSetGlobalRootSignature(
        &self,
        compiler: *mut IRCompilerOpaque,
        rootSignature: *const IRRootSignatureOpaque,
    ) {
        (self.IRCompilerSetGlobalRootSignature)(compiler, rootSignature)
    }
    #[doc = " Configure compiler compatibility flags.\n Compatibility flags allow you to tailor code generation to the specific requirements of your shaders.\n You typically enable compatibility flags to support a broader set of features and behaviors (such as out-of-bounds reads) when your shader needs them to operate correctly.\n These flags, however, carry a performance cost.\n Always use the minimum set of compatibility flags your shader needs to attain the highest runtime performance for IR code you compile.\n @param compiler the compiler to configure\n @param flags bitmask of compatibility flags to enable."]
    pub unsafe fn IRCompilerSetCompatibilityFlags(
        &self,
        compiler: *mut IRCompilerOpaque,
        flags: IRCompatibilityFlags,
    ) {
        (self.IRCompilerSetCompatibilityFlags)(compiler, flags)
    }
    #[doc = " Set primitive input topology\n Provides the compiler with information about input topology this shader will be used with.\n This information is required to correctly compile shaders that will render point primitive and may be used for other optimizations.\n @param compiler the compiler to configure\n @param inputTopology input topology"]
    pub unsafe fn IRCompilerSetInputTopology(
        &self,
        compiler: *mut IRCompilerOpaque,
        inputTopology: IRInputTopology,
    ) {
        (self.IRCompilerSetInputTopology)(compiler, inputTopology)
    }
    #[doc = " Enable geometry and tessellation emulation.\n @param compiler compiler to enable tessellation emulation\n @param enable pass in true to enable geometry emulation, false to disable it."]
    pub unsafe fn IRCompilerEnableGeometryAndTessellationEmulation(
        &self,
        compiler: *mut IRCompilerOpaque,
        enable: bool,
    ) {
        (self.IRCompilerEnableGeometryAndTessellationEmulation)(compiler, enable)
    }
    #[doc = " Enable dual-source blending support.\n When the configuration parameter is set to `IRDualSourceBlendingConfigurationDecideAtRuntime`, you must provide a function constant named \"`dualSourceBlendingEnabled`\" of type `uint8_t` at\n pipeline creation time, specifying whether to enable dual source blending.\n @param compiler compiler to configure.\n @param configuration set to enabled or disable to enable and disable support. Set to decide-at-runtime to control support at PSO-creation time via function constants.\n This parameter is reset after each compilation."]
    pub unsafe fn IRCompilerSetDualSourceBlendingConfiguration(
        &self,
        compiler: *mut IRCompilerOpaque,
        configuration: IRDualSourceBlendingConfiguration,
    ) {
        (self.IRCompilerSetDualSourceBlendingConfiguration)(compiler, configuration)
    }
    #[doc = " Enable depth feedback support.\n When the configuration parameter is set to `IRDepthWriteConfigurationDecideAtRuntime`, you must provide a function constant named \"`depthFeedbackEnabled`\" of type `uint8_t` at\n pipeline creation time, specifying whether to enable depth feedback.\n @param compiler compiler to configure.\n @param configuration set to enabled or disable to enable and disable support. Set to decide-at-runtime to control support at PSO-creation time via function constants.\n This parameter is reset after each compilation."]
    pub unsafe fn IRCompilerSetDepthFeedbackConfiguration(
        &self,
        compiler: *mut IRCompilerOpaque,
        configuration: IRDepthFeedbackConfiguration,
    ) {
        (self.IRCompilerSetDepthFeedbackConfiguration)(compiler, configuration)
    }
    #[doc = " Customize the name of the entry point functions generated by a compiler.\n @param compiler compiler to configure.\n @param newName name IRConverter assigns to the emited entry point."]
    pub unsafe fn IRCompilerSetEntryPointName(
        &self,
        compiler: *mut IRCompilerOpaque,
        newName: *const ::std::os::raw::c_char,
    ) {
        (self.IRCompilerSetEntryPointName)(compiler, newName)
    }
    #[doc = " Set the minimum GPU deployment target for MetalIR code generation.\n Targetting a newer family may enable the compiler to emit MetalIR further optimized for newer GPUs, but may render it incompatible with older models.\n @param compiler compiler to configure.\n @param family minimum GPU family supported by code generation."]
    pub unsafe fn IRCompilerSetMinimumGPUFamily(
        &self,
        compiler: *mut IRCompilerOpaque,
        family: IRGPUFamily,
    ) {
        (self.IRCompilerSetMinimumGPUFamily)(compiler, family)
    }
    #[doc = " Set the minimum operating system software version target for Metal IR code generation.\n Targetting a newer software version may enable the compiler to emi MetalIR further optimized for newer macOS and iOS releases, but it may render it incompatible with older operating system versions.\n Setting a minimum deployment target newer than your SDK may produce an `IRErrorCodeUnableToLinkModule` error.\n @param compiler compiler to configure.\n @param operatingSystem operating system name.\n @param version operating system version, such as \"13.0.0\" or \"16.0.0\"."]
    pub unsafe fn IRCompilerSetMinimumDeploymentTarget(
        &self,
        compiler: *mut IRCompilerOpaque,
        operatingSystem: IROperatingSystem,
        version: *const ::std::os::raw::c_char,
    ) {
        (self.IRCompilerSetMinimumDeploymentTarget)(compiler, operatingSystem, version)
    }
    #[doc = " Create an empty metallib binary.\n @return a new, empty metallib binary."]
    pub unsafe fn IRMetalLibBinaryCreate(&self) -> *mut IRMetalLibBinaryOpaque {
        (self.IRMetalLibBinaryCreate)()
    }
    #[doc = " Destroy a metallib binary.\n @param lib library to destroy."]
    pub unsafe fn IRMetalLibBinaryDestroy(&self, lib: *mut IRMetalLibBinaryOpaque) {
        (self.IRMetalLibBinaryDestroy)(lib)
    }
    #[doc = " Copy the bytecode from a metallib library into a byte array.\n @param lib metallib library from where to copy the bytecode.\n @param outBytecode into which to write the bytecode. This parameter must be an array of at least IRMetalLibGetBytecodeSize bytes.\n @return number of bytes written."]
    pub unsafe fn IRMetalLibGetBytecode(
        &self,
        lib: *const IRMetalLibBinaryOpaque,
        outBytecode: *mut u8,
    ) -> usize {
        (self.IRMetalLibGetBytecode)(lib, outBytecode)
    }
    #[doc = " Obtain the number of bytes needed to store the bytecode in a metallib.\n @param lib metallib to query.\n @return size in bytes needed to store the metallib's bytecode."]
    pub unsafe fn IRMetalLibGetBytecodeSize(&self, lib: *const IRMetalLibBinaryOpaque) -> usize {
        (self.IRMetalLibGetBytecodeSize)(lib)
    }
    #[doc = " Serialize an MetalIR object's shader bytecode to disk.\n @param outputPath path into which to write the serialized MetalIR.\n @param obj IRObject containing the bytecode to serialize.\n @param stage shader stage to serialize."]
    pub unsafe fn IRObjectSerialize(
        &self,
        outputPath: *const ::std::os::raw::c_char,
        obj: *const IRObjectOpaque,
        stage: IRShaderStage,
    ) -> bool {
        (self.IRObjectSerialize)(outputPath, obj, stage)
    }
    #[doc = " Create an empty reflection object.\n @return a new empty reflection object."]
    pub unsafe fn IRShaderReflectionCreate(&self) -> *mut IRShaderReflectionOpaque {
        (self.IRShaderReflectionCreate)()
    }
    #[doc = " Release a reflection object.\n @param reflection reflection object to release."]
    pub unsafe fn IRShaderReflectionDestroy(&self, reflection: *mut IRShaderReflectionOpaque) {
        (self.IRShaderReflectionDestroy)(reflection)
    }
    #[doc = " Obtain the name of the entry point from a reflection object.\n @return pointer to the name of the entry point. Do not free this pointer, its lifecycle is managed by, and coincides with, the reflection object's."]
    pub unsafe fn IRShaderReflectionGetEntryPointFunctionName(
        &self,
        reflection: *const IRShaderReflectionOpaque,
    ) -> *const ::std::os::raw::c_char {
        (self.IRShaderReflectionGetEntryPointFunctionName)(reflection)
    }
    #[doc = " Determine whether the shader requires supplemental information to operate correctly.\n @param reflection reflection object to evaluate.\n @return true if the compiled shader requires supplemental information in the form of function constants, false otherwise."]
    pub unsafe fn IRShaderReflectionNeedsFunctionConstants(
        &self,
        reflection: *const IRShaderReflectionOpaque,
    ) -> bool {
        (self.IRShaderReflectionNeedsFunctionConstants)(reflection)
    }
    #[doc = " Obtain the number of function constants in the reflection object.\n @param reflection reflection object to query.\n @return function constant count. May be zero if the shader stage to which this reflection corresponds has no function constants."]
    pub unsafe fn IRShaderReflectionGetFunctionConstantCount(
        &self,
        reflection: *const IRShaderReflectionOpaque,
    ) -> usize {
        (self.IRShaderReflectionGetFunctionConstantCount)(reflection)
    }
    #[doc = " Copy function constant reflection data from a reflection object to an array.\n You are responsible for calling IRShaderReflectionReleaseFunctionConstants on the array to ensure copied function constant reflection data are released.\n @param reflection reflection object to query.\n @param functionConstants function constants array into which to write the reflection data. This object needs to be able to store at least\n IRShaderReflectionFunctionConstantCount function constants."]
    pub unsafe fn IRShaderReflectionCopyFunctionConstants(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        functionConstants: *mut IRFunctionConstant,
    ) {
        (self.IRShaderReflectionCopyFunctionConstants)(reflection, functionConstants)
    }
    #[doc = " Release function constant data.\n @param functionConstants array of function constants.\n @param functionConstantCount number of function constants in the array."]
    pub unsafe fn IRShaderReflectionReleaseFunctionConstants(
        &self,
        functionConstants: *mut IRFunctionConstant,
        functionConstantCount: usize,
    ) {
        (self.IRShaderReflectionReleaseFunctionConstants)(functionConstants, functionConstantCount)
    }
    #[doc = " Copy shader reflection for a compute stage.\n @param reflection reflection object to query.\n @param version version of the reflection data to obtain.\n @param csinfo pointer to a versioned CS Info struct into which to copy the reflection data for the stage. You must release the contents of this stuct by calling IRShaderReflectionReleaseComputeInfo.\n @return true if the reflection object contains compute reflection information for the specified version."]
    pub unsafe fn IRShaderReflectionCopyComputeInfo(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        csinfo: *mut IRVersionedCSInfo,
    ) -> bool {
        (self.IRShaderReflectionCopyComputeInfo)(reflection, version, csinfo)
    }
    #[doc = " Copy shader reflection for a vertex stage.\n @param reflection reflection object to query.\n @param version version of the reflection data to obtain.\n @param vsinfo pointer to a versioned VS Info struct into which to copy the reflection data for the stage.  You must release the contents of this stuct by calling IRShaderReflectionReleaseVertexInfo.\n @return true if the reflection object contains vertex stage reflection information for the specified version."]
    pub unsafe fn IRShaderReflectionCopyVertexInfo(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        vsinfo: *mut IRVersionedVSInfo,
    ) -> bool {
        (self.IRShaderReflectionCopyVertexInfo)(reflection, version, vsinfo)
    }
    #[doc = " Copy shader reflection for a fragment stage.\n @param reflection reflection object to query.\n @param version version of the reflection data to obtain.\n @param fsinfo pointer to a versioned FS Info struct into which to copy the reflection data for the stage.  You must release the contents of this stuct by calling IRShaderReflectionReleaseFragmentInfo.\n @return true if the reflection object contains fragment stage reflection information for the specified version."]
    pub unsafe fn IRShaderReflectionCopyFragmentInfo(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        fsinfo: *mut IRVersionedFSInfo,
    ) -> bool {
        (self.IRShaderReflectionCopyFragmentInfo)(reflection, version, fsinfo)
    }
    #[doc = " Copy shader reflection for a geometry stage.\n @param reflection reflection object to query.\n @param version version of the reflection data to obtain.\n @param gsinfo pointer to a versioned GS Info struct into which to copy the reflection data for the stage. You must release the contents of this stuct by calling IRShaderReflectionReleaseGeometryInfo.\n @return true if the reflection object contains geometry stage reflection information for the specified version."]
    pub unsafe fn IRShaderReflectionCopyGeometryInfo(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        gsinfo: *mut IRVersionedGSInfo,
    ) -> bool {
        (self.IRShaderReflectionCopyGeometryInfo)(reflection, version, gsinfo)
    }
    #[doc = " Copy shader reflection for a hull shader stage.\n @param reflection reflection object to query.\n @param version version of the reflection data to obtain.\n @param hsinfo pointer to a versioned HS Info struct into which to copy the reflection data for the stage. You must release the contents of this stuct by calling IRShaderReflectionReleaseHullInfo.\n @return true if the reflection object contains hull shader stage reflection information for the specified version."]
    pub unsafe fn IRShaderReflectionCopyHullInfo(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        hsinfo: *mut IRVersionedHSInfo,
    ) -> bool {
        (self.IRShaderReflectionCopyHullInfo)(reflection, version, hsinfo)
    }
    #[doc = " Copy shader reflection for a domain shader stage.\n @param reflection reflection object to query.\n @param version version of the reflection data to obtain.\n @param dsinfo pointer to a versioned DS Info struct into which to copy the reflection data for the stage.  You must release the contents of this stuct by calling IRShaderReflectionReleaseDomainInfo.\n @return true if the reflection object contains domain shader stage reflection information for the specified version."]
    pub unsafe fn IRShaderReflectionCopyDomainInfo(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        version: IRReflectionVersion,
        dsinfo: *mut IRVersionedDSInfo,
    ) -> bool {
        (self.IRShaderReflectionCopyDomainInfo)(reflection, version, dsinfo)
    }
    #[doc = " Release versioned compute information.\n @param csinfo pointer to the compute shader reflection information to release.\n @return false if the csinfo version is an unrecognized version or the csinfo pointer is null."]
    pub unsafe fn IRShaderReflectionReleaseComputeInfo(
        &self,
        csinfo: *mut IRVersionedCSInfo,
    ) -> bool {
        (self.IRShaderReflectionReleaseComputeInfo)(csinfo)
    }
    #[doc = " Release versioned vertex stage information.\n @param vsinfo pointer to the vertex shader reflection information to release.\n @return false if the vsinfo version is an unrecognized version or the vsinfo pointer is null."]
    pub unsafe fn IRShaderReflectionReleaseVertexInfo(
        &self,
        vsinfo: *mut IRVersionedVSInfo,
    ) -> bool {
        (self.IRShaderReflectionReleaseVertexInfo)(vsinfo)
    }
    #[doc = " Release versioned fragment stage information.\n @param fsinfo pointer to the fragment shader reflection information to release.\n @return false if the fsinfo version is an unrecognized version or the fsinfo pointer is null."]
    pub unsafe fn IRShaderReflectionReleaseFragmentInfo(
        &self,
        fsinfo: *mut IRVersionedFSInfo,
    ) -> bool {
        (self.IRShaderReflectionReleaseFragmentInfo)(fsinfo)
    }
    #[doc = " Release versioned geometry stage information.\n @param gsinfo pointer to the geometry shader reflection information to release.\n @return false if the gsinfo version is an unrecognized version or the gsinfo pointer is null."]
    pub unsafe fn IRShaderReflectionReleaseGeometryInfo(
        &self,
        gsinfo: *mut IRVersionedGSInfo,
    ) -> bool {
        (self.IRShaderReflectionReleaseGeometryInfo)(gsinfo)
    }
    #[doc = " Release versioned hull stage information.\n @param hsinfo pointer to the hull shader reflection information to release.\n @return false if the hsinfo version is an unrecognized version or the hsinfo pointer is null."]
    pub unsafe fn IRShaderReflectionReleaseHullInfo(&self, hsinfo: *mut IRVersionedHSInfo) -> bool {
        (self.IRShaderReflectionReleaseHullInfo)(hsinfo)
    }
    #[doc = " Release versioned domain stage information.\n @param dsinfo pointer to the domain shader reflection information to release.\n @return false if the dsinfo version is an unrecognized version or the dsinfo pointer is null."]
    pub unsafe fn IRShaderReflectionReleaseDomainInfo(
        &self,
        dsinfo: *mut IRVersionedDSInfo,
    ) -> bool {
        (self.IRShaderReflectionReleaseDomainInfo)(dsinfo)
    }
    #[doc = " Obtain the number of resources referenced by the top-level argument buffer\n @param reflection the reflection object for which to obtain the resource count.\n @return number of resources the top-level argument buffer references."]
    pub unsafe fn IRShaderReflectionGetResourceCount(
        &self,
        reflection: *const IRShaderReflectionOpaque,
    ) -> usize {
        (self.IRShaderReflectionGetResourceCount)(reflection)
    }
    #[doc = " Get the locations within the top-level Argument Buffer for all top-level resources.\n @param reflection the reflection object resulting from the compilation process.\n @param resourceLocations parameter into which to write resource locations. This array must contain enough storage to write IRShaderReflectionGetResourceCount() elements.\n @note string references within the resource locations are pointers into the reflection object. The reflection object's lifecycle must be preserved while accessing these strings. Names may be NULL."]
    pub unsafe fn IRShaderReflectionGetResourceLocations(
        &self,
        reflection: *const IRShaderReflectionOpaque,
        resourceLocations: *mut IRResourceLocation,
    ) {
        (self.IRShaderReflectionGetResourceLocations)(reflection, resourceLocations)
    }
    #[doc = " Obtain the number of resources referenced in a top-level Argument Buffer using a hierarchical layout.\n @param rootSignature root signature corresponding to the hierarchical layout definition.\n @return number of resources the top-level argument buffer references."]
    pub unsafe fn IRRootSignatureGetResourceCount(
        &self,
        rootSignature: *const IRRootSignatureOpaque,
    ) -> usize {
        (self.IRRootSignatureGetResourceCount)(rootSignature)
    }
    #[doc = " Get the locations of resources in the top-level Argument Buffer.\n @param rootSignature root signature corresponding to the hierarchical layout definition.\n @param resourceLocations parameter into which to write resource locations. This array must contain enough storage to write IRRootSignatureGetResourceCount() elements."]
    pub unsafe fn IRRootSignatureGetResourceLocations(
        &self,
        rootSignature: *const IRRootSignatureOpaque,
        resourceLocations: *mut IRResourceLocation,
    ) {
        (self.IRRootSignatureGetResourceLocations)(rootSignature, resourceLocations)
    }
    #[doc = " Serialize reflection information into JSON.\n @param reflection reflection object.\n @return null-terminated string containing JSON. You are responsible for freeing this string."]
    pub unsafe fn IRShaderReflectionSerialize(
        &self,
        reflection: *mut IRShaderReflectionOpaque,
    ) -> *const ::std::os::raw::c_char {
        (self.IRShaderReflectionSerialize)(reflection)
    }
    #[doc = " Deserialize a JSON string into a reflection object.\n @param blob null-terminated JSON string containing reflection information.\n @param reflection reflection object into which to deserialize."]
    pub unsafe fn IRShaderReflectionDeserialize(
        &self,
        blob: *const ::std::os::raw::c_char,
        reflection: *mut IRShaderReflectionOpaque,
    ) {
        (self.IRShaderReflectionDeserialize)(blob, reflection)
    }
}
